### ISSUE TITLE
Add option for choosing the number of threads used by argon2

### ISSUE THREAD

**Issue by hamiltonp** [jsfierro/jfpg#1]
It's my suggestion, because most processors today have 4 threads or more, mine has 8.

I made a lammer-ish hack in the ./include/defines.h file and worked fine.

#define	ARGON2_T	4000	/* Number of default iterations */
#define ARGON2_MEM	32	/* Default RAM used in MiB */
#define ARGON2_P	 8	/* Default number of threads */
#define MIN_ROUNDS      2000	/* Minimum iterations */
#define MAX_ROUNDS      6000	/* Maximum iterations */
#define	MIN_MEM		16	/* Minimum RAM in MiB */
#define	MAX_MEM		64	/* Maximum RAM in MiB */

**Comment by jsfierro** [comment]
I'm okay with adding this. Generally speaking, you'll want the number of threads to be double the number of physical processor cores for best performance.

**Comment by jsfierro** [comment]
This feature has been added. See commit [4c1c68550026f46fdcf2a94aa9f909861d43fe9c](https://github.com/jsfierro/jfpg/commit/4c1c68550026f46fdcf2a94aa9f909861d43fe9c)

**Comment by hamiltonp** [comment]
Thank you very much, it's the only feature was lacking for me.
